de:
  languageCode: de-DE
  languageName: deutsch
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Töpferkönig. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Töpferkönig"
  contentDir: content/de
  params:
    description: "Site Description"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Impressum"
      help_url: "example-page/"
    ### calls to action ###
    main_cta:
      text: "Töpferkönig 2024"
      link: "faq/"
    footer_cta:
      text: "Töpferkönig 2024"
      link: "faq/"
    github_edit: ""
  ### example menu showing children ###
  menu:
    main:
    - identifier: "blog"
      name: "News"
      url: "blog/"
      weight: 1
    - identifier: "about"
      name: "About"
      url: "example-page/"
      weight: 2
    - identifier: "child-1"
      name: "Example Child Page"
      url: "example-page/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "about"
    - identifier: "child-2"
      name: "Example Child Page"
      url: "example-page/"
      weight: 2
      post: "Aenean commodo ligula get dolor. Aenean massa."
      parent: "about"
    - identifier: "child-3"
      name: "Example Child Page"
      url: "example-page/"
      weight: 3
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "about"
    - identifier: "example"
      name: "Example"
      url: "example-page/"
      weight: 3
    - identifier: "example-1"
      name: "Example Child Page"
      url: "example-page/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "example"
    - identifier: "example-2"
      name: "Example Child Page"
      url: "example-page/"
      weight: 2
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "example"
    - identifier: "example-3"
      name: "Example Child Page"
      url: "example-page/"
      weight: 3
      post: "Aenean commodo ligula get dolor. Aenean massa. "
      parent: "example"
    - identifier: "demo-page"
      name: "Demo Page"
      url: "demo-page/"
      weight: 4
en:
  languageCode: en-US
  languageName: english
  weight: 2
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Töpferkönig. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Töpferkönig"
  contentDir: content/en
  params:
    description: "Site Description"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Impressum"
      help_url: "example-page/"
    ### calls to action ###
    main_cta:
      text: "Töpferkönig 2024"
      link: "faq/"
    footer_cta:
      text: "Töpferkönig 2024"
      link: "faq/"
    github_edit: ""
  ### example menu showing children ###
  menu:
    main:
    - identifier: "blog"
      name: "News"
      url: "blog/"
      weight: 1
    - identifier: "about"
      name: "About"
      url: "example-page/"
      weight: 2
    - identifier: "child-1"
      name: "Example Child Page"
      url: "example-page/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "about"
    - identifier: "child-2"
      name: "Example Child Page"
      url: "example-page/"
      weight: 2
      post: "Aenean commodo ligula get dolor. Aenean massa."
      parent: "about"
    - identifier: "child-3"
      name: "Example Child Page"
      url: "example-page/"
      weight: 3
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "about"
    - identifier: "example"
      name: "Example"
      url: "example-page/"
      weight: 3
    - identifier: "example-1"
      name: "Example Child Page"
      url: "example-page/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "example"
    - identifier: "example-2"
      name: "Example Child Page"
      url: "example-page/"
      weight: 2
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "example"
    - identifier: "example-3"
      name: "Example Child Page"
      url: "example-page/"
      weight: 3
      post: "Aenean commodo ligula get dolor. Aenean massa. "
      parent: "example"
    - identifier: "demo-page"
      name: "Demo Page"
      url: "demo-page/"
      weight: 4
  
cs:
  languageCode: cs-CZ
  languageName: čeština
  weight: 3
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Töpferkönig. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Töpferkönig"
  contentDir: content/cs
  params:
    description: "Site Description"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Impressum"
      help_url: "example-page/"
    ### calls to action ###
    main_cta:
      text: "Töpferkönig 2024"
      link: "faq/"
    footer_cta:
      text: "Töpferkönig 2024"
      link: "faq/"
    github_edit: ""
  ### example menu showing children ###
  menu:
    main:
    - identifier: "blog"
      name: "News"
      url: "blog/"
      weight: 1
    - identifier: "about"
      name: "About"
      url: "example-page/"
      weight: 2
    - identifier: "child-1"
      name: "Example Child Page"
      url: "example-page/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "about"
    - identifier: "child-2"
      name: "Example Child Page"
      url: "example-page/"
      weight: 2
      post: "Aenean commodo ligula get dolor. Aenean massa."
      parent: "about"
    - identifier: "child-3"
      name: "Example Child Page"
      url: "example-page/"
      weight: 3
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "about"
    - identifier: "example"
      name: "Example"
      url: "example-page/"
      weight: 3
    - identifier: "example-1"
      name: "Example Child Page"
      url: "example-page/"
      weight: 1
      post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
      parent: "example"
    - identifier: "example-2"
      name: "Example Child Page"
      url: "example-page/"
      weight: 2
      post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "example"
    - identifier: "example-3"
      name: "Example Child Page"
      url: "example-page/"
      weight: 3
      post: "Aenean commodo ligula get dolor. Aenean massa. "
      parent: "example"
    - identifier: "demo-page"
      name: "Demo Page"
      url: "demo-page/"
      weight: 4
pl:
  languageCode: pl-PL
  languageName: polski
  contentDir: content/pl
  weight: 4
  title: "Título del Sitio"
  params:
    description: "Descripción del Sitio"
  menu:
    main:
    - identifier: "about"
      name: "Acerca de"
      url: "example-page/"
      weight: 1
    - identifier: "child-1"
      name: "Página Hija de Ejemplo"
      url: "example-page/"
      weight: 1
      parent: "about"
    - identifier: "faq"
      name: "TK 2024"
      url: "faq/"
      weight: 3
    - identifier: "blog"
      name: "Blog"
      url: "blog/"
      weight: 2
