######################## production configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL: https://www.toepferkoenig.com/
googleAnalytics:
enableRobotsTXT: true
build:
  writeStats: true
